import React, { useState } from 'react';
import {
  Sparkles,
  Volume2,
  VolumeX,
  ArrowRight,
  Lightbulb,
  AlertTriangle,
  CheckCircle,
  Copy,
  Check,
  FileText,
  Target,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { DoubtResponse, ExplanationStyle, SubjectCategory } from '../types';

interface DoubtSolverProps {
  subject: SubjectCategory;
  customSubject: string;
  onNavigateToNotes: (topic: string, textContext?: string) => void;
  onNavigateToQuiz: (topic: string) => void;
}

const SAMPLE_DOUBTS: {
  subject: string;
  question: string;
  style: ExplanationStyle;
}[] = [
  {
    subject: 'Computer Science & AI',
    question:
      'Explain Big O Notation and space vs time complexity simply with real examples.',
    style: 'feynman',
  },
  {
    subject: 'Computer Science & AI',
    question:
      'How do Attention Mechanisms in AI Transformers work step-by-step?',
    style: 'step_by_step',
  },
  {
    subject: 'Mathematics & Statistics',
    question:
      'What is the intuitive meaning of the Derivative vs Integral in Calculus?',
    style: 'analogies',
  },
  {
    subject: 'Physics & Engineering',
    question:
      'Explain Quantum Entanglement and Superposition without complex math equations.',
    style: 'feynman',
  },
  {
    subject: 'Chemistry & Biology',
    question:
      'How does ATP Synthase convert energy in the Mitochondria?',
    style: 'step_by_step',
  },
  {
    subject: 'Economics & Business',
    question:
      'What is the difference between Inflation, Deflation, and Stagflation?',
    style: 'standard',
  },
  {
    subject: 'Psychology & Humanities',
    question:
      'Explain Cognitive Dissonance theory with everyday human examples.',
    style: 'analogies',
  },
];

export const DoubtSolver: React.FC<DoubtSolverProps> = ({
  subject,
  customSubject,
  onNavigateToNotes,
  onNavigateToQuiz,
}) => {
  const [question, setQuestion] = useState('');
  const [style, setStyle] =
    useState<ExplanationStyle>('feynman');
  const [contextText, setContextText] = useState('');
  const [showContext, setShowContext] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [response, setResponse] =
    useState<DoubtResponse | null>(null);

  const [isSpeaking, setIsSpeaking] = useState(false);
  const [copied, setCopied] = useState(false);
  const [checkedTakeaways, setCheckedTakeaways] =
    useState<Record<number, boolean>>({});

  const activeSubjectName =
    subject === 'Custom'
      ? customSubject || 'General'
      : subject;

  const handleSolve = async (
    overrideQuestion?: string,
    overrideStyle?: ExplanationStyle
  ) => {
    const qToSolve = overrideQuestion || question;
    const styleToUse = overrideStyle || style;

    if (!qToSolve.trim()) {
      setError('Please enter your study doubt or question.');
      return;
    }

    setLoading(true);
    setError(null);
    setResponse(null);
    setCheckedTakeaways({});

    try {
      const apiKey = (import.meta as any).env.VITE_GEMINI_API_KEY;

if (!apiKey) {
  throw new Error("Gemini API key is missing.");
}

const promptText = "Explain the student question clearly.";

const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

const res = await fetch(apiUrl, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    contents: [
      {
        parts: [
          {
            text: promptText,
          },
        ],
      },
    ],
  }),
});

      if (!res.ok) {
        const errData = await res
          .json()
          .catch(() => ({}));

        throw new Error(
          errData?.error?.message ||
            `Gemini API error: ${res.status}`
        );
      }

      const data = await res.json();

      const rawText =
        data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!rawText) {
        throw new Error(
          'No response was generated by Gemini.'
        );
      }

      const parsedResponse =
        JSON.parse(rawText) as DoubtResponse;

      setResponse(parsedResponse);
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : 'Failed to solve doubt. Please check your API key and network connection.';

      setError(message);
    } finally {
      setLoading(false);
    }
  };

  const toggleSpeak = () => {
    if (!response) return;

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    window.speechSynthesis.cancel();

    const cleanAnswer = response.answer.replace(
      /[*#_]/g,
      ''
    );

    const textToSpeak =
      `${response.summary}. ${cleanAnswer}`;

    const utterance =
      new SpeechSynthesisUtterance(textToSpeak);

    utterance.rate = 1.0;

    utterance.onend = () => {
      setIsSpeaking(false);
    };

    utterance.onerror = () => {
      setIsSpeaking(false);
    };

    window.speechSynthesis.speak(utterance);
    setIsSpeaking(true);
  };

  const handleCopy = async () => {
    if (!response) return;

    const fullText = `### ${question}

**Summary:** ${response.summary}

${response.answer}

**Key Takeaways:**
${response.keyTakeaways
  .map((item) => `- ${item}`)
  .join('\n')}`;

    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);

      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch {
      setError('Unable to copy the explanation.');
    }
  };

  return (
    <div className="space-y-6">

      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg">
        <div className="flex items-center space-x-2 text-indigo-400 text-xs font-semibold uppercase tracking-wider mb-1">
          <Sparkles className="w-4 h-4" />
          <span>
            AI Academic Mentor • {activeSubjectName}
          </span>
        </div>

        <h2 className="text-xl sm:text-2xl font-bold text-white">
          Ask Any College Study Doubt
        </h2>

        <p className="text-slate-400 text-xs sm:text-sm mt-1">
          Get instant, deep, or Feynman-style explanations
          tailored to your subject level.
        </p>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-md space-y-4">

        <div>
          <label
            htmlFor="doubt-question-input"
            className="block text-xs font-semibold text-slate-300 mb-2"
          >
            What concept or problem are you stuck on?
          </label>

          <textarea
            id="doubt-question-input"
            value={question}
            onChange={(e) =>
              setQuestion(e.target.value)
            }
            placeholder="Example: What is cloud computing?"
            rows={3}
            className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 resize-none"
          />
        </div>

        <div>
          <span className="block text-xs font-semibold text-slate-300 mb-2">
            Explanation Approach:
          </span>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {[
              {
                id: 'feynman',
                label: '💡 Feynman',
                desc: 'Simple explanation',
              },
              {
                id: 'standard',
                label: '🎓 Standard',
                desc: 'Detailed explanation',
              },
              {
                id: 'analogies',
                label: '🔮 Analogies',
                desc: 'Real-world examples',
              },
              {
                id: 'step_by_step',
                label: '🔢 Step-by-Step',
                desc: 'Logical breakdown',
              },
            ].map((item) => (
              <button
                key={item.id}
                type="button"
                onClick={() =>
                  setStyle(
                    item.id as ExplanationStyle
                  )
                }
                className={`p-2.5 rounded-xl text-left border transition-all ${
                  style === item.id
                    ? 'bg-indigo-600/20 border-indigo-500 text-white'
                    : 'bg-slate-950/60 border-slate-800 text-slate-400'
                }`}
              >
                <div className="text-xs font-semibold">
                  {item.label}
                </div>

                <div className="text-[10px] text-slate-400 mt-0.5">
                  {item.desc}
                </div>
              </button>
            ))}
          </div>
        </div>

        <div>
          <button
            type="button"
            onClick={() =>
              setShowContext(!showContext)
            }
            className="text-xs text-indigo-400 font-medium"
          >
            {showContext
              ? '─ Hide Additional Context'
              : '+ Add Textbook Context'}
          </button>

          {showContext && (
            <textarea
              value={contextText}
              onChange={(e) =>
                setContextText(e.target.value)
              }
              placeholder="Paste textbook content or problem statement..."
              rows={3}
              className="mt-2 w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-200"
            />
          )}
        </div>

        <div className="flex items-center justify-between pt-2 border-t border-slate-800">

          <div className="text-xs text-slate-500 hidden sm:block">
            Powered by Gemini AI
          </div>

          <button
            type="button"
            disabled={
              loading || !question.trim()
            }
            onClick={() => handleSolve()}
            className="w-full sm:w-auto px-6 py-2.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white font-semibold text-xs rounded-xl flex items-center justify-center space-x-2"
          >
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                <span>
                  Analyzing & Solving...
                </span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>
                  Explain Concept & Solve Doubt
                </span>
              </>
            )}
          </button>
        </div>
      </div>

      {!response && !loading && (
        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-4">

          <div className="text-xs font-semibold text-slate-400 mb-2 flex items-center gap-1.5">
            <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
            <span>
              Popular College Doubt Prompts
            </span>
          </div>

          <div className="flex flex-wrap gap-2">
            {SAMPLE_DOUBTS.map((item, index) => (
              <button
                key={index}
                type="button"
                onClick={() => {
                  setQuestion(item.question);
                  setStyle(item.style);
                  handleSolve(
                    item.question,
                    item.style
                  );
                }}
                className="text-xs bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800 rounded-lg px-3 py-1.5"
              >
                <span className="text-indigo-400 font-semibold mr-1">
                  [{item.subject.split(' ')[0]}]
                </span>
                {item.question}
              </button>
            ))}
          </div>
        </div>
      )}

      {error && (
        <div className="bg-rose-950/40 border border-rose-800/60 rounded-xl p-4 text-xs text-rose-300 flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0" />

          <div>
            <span className="font-semibold">
              Error:
            </span>{' '}
            {error}
          </div>
        </div>
      )}

      {loading && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4 animate-pulse">
          <div className="h-4 bg-slate-800 rounded w-1/4" />
          <div className="h-20 bg-slate-800/60 rounded-xl" />
          <div className="h-32 bg-slate-800/40 rounded-xl" />
        </div>
      )}

      {response && !loading && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">

          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">

            <div>
              <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">
                Concept Breakdown •{' '}
                {style.toUpperCase()}
              </span>

              <h3 className="text-lg font-bold text-white mt-0.5">
                {question}
              </h3>
            </div>

            <div className="flex items-center space-x-2">

              <button
                type="button"
                onClick={toggleSpeak}
                className="px-3 py-1.5 rounded-lg text-xs font-medium border flex items-center space-x-1.5 bg-slate-800 border-slate-700 text-slate-300"
              >
                {isSpeaking ? (
                  <VolumeX className="w-3.5 h-3.5" />
                ) : (
                  <Volume2 className="w-3.5 h-3.5" />
                )}

                <span>
                  {isSpeaking
                    ? 'Stop Audio'
                    : 'Listen Answer'}
                </span>
              </button>

              <button
                type="button"
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-lg text-xs font-medium bg-slate-800 border border-slate-700 text-slate-300 flex items-center space-x-1.5"
              >
                {copied ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}

                <span>
                  {copied
                    ? 'Copied!'
                    : 'Copy Explanation'}
                </span>
              </button>

            </div>
          </div>

          <div className="bg-indigo-950/30 border border-indigo-800/50 rounded-xl p-4 flex items-start gap-3">

            <Lightbulb className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />

            <div>
              <div className="text-xs font-bold text-indigo-300 uppercase tracking-wider">
                Executive Summary
              </div>

              <p className="text-sm text-slate-200 mt-1 leading-relaxed font-medium">
                {response.summary}
              </p>
            </div>
          </div>

          <div className="prose prose-invert max-w-none text-slate-300 text-sm leading-relaxed border-b border-slate-800 pb-6">
            <ReactMarkdown>
              {response.answer}
            </ReactMarkdown>
          </div>

          {response.analogies && (
            <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4">

              <div className="text-xs font-bold text-cyan-400 uppercase tracking-wider mb-1">
                🔮 Mental Model & Analogy
              </div>

              <p className="text-xs sm:text-sm text-slate-300 italic">
                {response.analogies}
              </p>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4">

              <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 text-emerald-400" />
                <span>Exam Essentials</span>
              </h4>

              <ul className="space-y-2">
                {response.keyTakeaways.map(
                  (item, index) => (
                    <li
                      key={index}
                      onClick={() =>
                        setCheckedTakeaways(
                          (previous) => ({
                            ...previous,
                            [index]:
                              !previous[index],
                          })
                        )
                      }
                      className="flex items-start gap-2.5 text-xs text-slate-300 cursor-pointer"
                    >
                      <input
                        type="checkbox"
                        checked={
                          !!checkedTakeaways[index]
                        }
                        readOnly
                        className="mt-0.5"
                      />

                      <span
                        className={
                          checkedTakeaways[index]
                            ? 'line-through text-slate-500'
                            : ''
                        }
                      >
                        {item}
                      </span>
                    </li>
                  )
                )}
              </ul>
            </div>

            <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4">

              <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-amber-400" />
                <span>
                  Common Traps & Misconceptions
                </span>
              </h4>

              <ul className="space-y-2">
                {response.commonMisconceptions.map(
                  (item, index) => (
                    <li
                      key={index}
                      className="text-xs text-slate-300 flex items-start gap-2"
                    >
                      <span className="text-amber-400 font-bold">
                        •
                      </span>
                      <span>{item}</span>
                    </li>
                  )
                )}
              </ul>
            </div>

          </div>

          <div className="pt-2 border-t border-slate-800 space-y-3">

            <div className="text-xs font-semibold text-slate-400">
              Deepen Your Understanding:
            </div>

            <div className="flex flex-wrap gap-2">
              {response.suggestedFollowUps.map(
                (item, index) => (
                  <button
                    key={index}
                    type="button"
                    onClick={() => {
                      setQuestion(item);
                      handleSolve(item, style);
                    }}
                    className="text-xs bg-slate-950 hover:bg-indigo-950/60 text-slate-300 border border-slate-800 rounded-xl px-3 py-2 text-left flex items-center gap-1.5"
                  >
                    <span>{item}</span>
                    <ArrowRight className="w-3 h-3 text-indigo-400 shrink-0" />
                  </button>
                )
              )}
            </div>

            <div className="flex flex-wrap items-center justify-end gap-3 pt-4 border-t border-slate-800/60">

              <button
                type="button"
                onClick={() =>
                  onNavigateToNotes(
                    question,
                    response.answer
                  )
                }
                className="px-4 py-2 bg-slate-800 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 flex items-center gap-1.5"
              >
                <FileText className="w-4 h-4 text-indigo-400" />
                <span>
                  Generate Full Study Notes
                </span>
              </button>

              <button
                type="button"
                onClick={() =>
                  onNavigateToQuiz(question)
                }
                className="px-4 py-2 bg-indigo-600 text-white text-xs font-semibold rounded-xl flex items-center gap-1.5"
              >
                <Target className="w-4 h-4" />
                <span>
                  Test Knowledge With Quiz
                </span>
              </button>

            </div>
          </div>

        </div>
      )}
    </div>
  );
};